### PR TITLE
yii2

### PR DESCRIPTION
**Pull request by githubjeka**

### CODE REVIEW

**Comment by Big-Shark** [comment]
Please merge commits and update PR.

**Comment by githubjeka** [comment]
???

> This branch has no conflicts with the base branch

**Comment by Big-Shark** [comment]
@githubjeka no have

**Comment by githubjeka** [comment]
image

**Comment by githubjeka** [comment]
On windows doesn't work still :(

**Comment by githubjeka** [comment]
Yii2 tests ready for merge!

**Pull request merged**
